tiffanyhansy/devcourse-runtime

public/small_icon.svg
src/routes/Main/CenterContents/Calender/ToDo.tsx
src/routes/Main/CenterContents/Calender/ToDoListItem.tsx

- ToDo 리스트 아이템 컴포넌트 만들었습니다.
- feat/post-header-dev
- 따봉~

📝 feat/post-header-dev: ToDo리스트 아이템 컴포넌트 퍼블리싱

---

.gitignore
package.json
pnpm-lock.yaml
src/App.tsx

- main페이지 max-width를 1440으로 고정하고 나머지 여백은 margin 줬습니당
- header도 수정해서 한 번 더 보낼 예정이에요!!

📝 feat/post-main : main페이지 규격 수정(max-width값이랑 margin값 추가)

---

src/components/Form/FormContainer.tsx
src/components/Form/Input.tsx
src/components/Form/LoginButton.tsx
src/routes/Login/Login.tsx

from container, input창, 로그인/회원가입시 사용할 버튼을 컴포넌트로 만들었습니다
로그인 창을 만들었습니다.
style/login
SubimtButton은 빈 파일인데 잘못 들어갔습니다. 추후 삭제하겠습니당
제대로 짰는지 모르겠네요.. 이상한 부분 있으면 말씀해주세요!

💄style: 로그인 페이지 퍼블리싱

---

src/routes/Join/Join.tsx

회원가입 창을 만들었습니다.
맨 위에 import React from "react"; 부분은 바로 빼도록 하겠습니당 ㅎㅎ
style/join
이상하게 코드 짠 부분 있으면 말해주세용!!

💄 style/회원가입 창 퍼블리싱

---

src/routes/Main/CenterContents/Calender/ToDoListItem.tsx
src/store/store.ts

- store.tsx 끝 부분 지워진거 복구했습니다
- ToDoListItem img 태그에 빈문자열이 있었는데 삭제했습니다
Feat/post-main-fix
- 히히

Feat/post main fix: 각종 에러사항 수정

---

src/components/Mui/Fab.tsx
src/routes/Main/CenterContents/Calender/ToDoEditor.tsx
src/routes/Main/CenterContents/Calender/ToDoListItem.tsx
src/routes/Main/Main.tsx
src/routes/Main/RightComponent/FriendList.tsx

- todo 입력창 style 수정
- 메인페이지 style 수정
- todo 체크박스가 잘 눌리지 않는 error 해결
- 타이머 재생 중일 때 play 버튼 색 타이머와 동일하도록 변경 
- style/todo ➡️ main
pull 하신 후에 스타일 잘 적용되었는지 확인 부탁드립니다! 💡

style: 메인페이지 style 수정 

---

src/routes/Main/LeftContents/TimerComponent/Timer.tsx
src/routes/Main/LeftContents/TimerComponent/TimerComponent.tsx
src/store/store.ts

- 타이머가 목표시간을 달성하면 색상이 변경됩니다.
- isAcheve 변수를 통해 추후에 목표시간 달성시 애니메이션 효과 + 글 작성시 오늘의 목표시간 달성 여부 등을 추가시킬 계획입니다.
- Feat/post-main-update
- 배고파요

📝 Feat/post main update : 타이머 목표시간 달성시 변경되는 isAchieve 상태/핸들러 store에 추가 + 달성시 타이머 색상 변경 기능 추가

---

src/routes/Main/Main.tsx

- 메인페이지 Button이랑 KeyboardArrowRightRoundedIcon 컴포넌트화 시키면서 import 뺐었는데 다시 추가했습니다.
+) 목표설정 기능은 컴포넌트로 따로 만들어 놔서 디자인 완료하시면 pull 받아서 기능 넣겠습니다!!
- feat/post-main-fix
- 간단한 오류 수정입니다!

🐛 feat/post-main-fix : 메인페이지에 컴포넌트 import

---

src/components/howTime/HowTimeModal.tsx
src/routes/Main/Main.tsx

- ~님의 오늘 공부 시간은? 모달창 아래 공백이 생기고 스크롤이 되는 오류 해결 
- style/main-timer ➡️ main
**브랜치 삭제하지 말아주세요! 같은 브랜치에서 버튼 스타일링도 할 예정입니다**

🩹 fix: 오늘 공부 시간? 화면이 스크롤 되는 오류 해결

---

src/store/store.ts

- store에 잘렸던 코드 복구했습니당
- feat/post-store-fix : store
- 하잉

🐛 feat/post-store-fix : store 잘린 코드 수정

---

src/routes/Join/Join.tsx
src/routes/Login/Login.tsx

-alert 위치 변경하였습니당
feat/form
감사합니당!

💄 style: alert 위치 변경

---

src/App.tsx
src/asset/images/Icon.svg
src/components/404Page/ErrorPage.tsx
src/components/Modal/FriendManageModal.tsx
src/components/Modal/ProfileModal.tsx
src/components/Mui/List.tsx
src/routes/LayOut/Header.tsx
src/routes/Main/LeftContents/ButtonListComponent/ButtonListComponent.tsx
src/routes/Main/Main.tsx
src/store/store.ts

- 친구관리 페이지 추가
- svg 1개 추가
- Main.tsx : 친구관리 모달 추가
- FriendManage.tsx 추가 : 친구관리 페이지
- store.ts : 친구관리 상태 추가
- ButtinListComponent.tsx : 친구관리 모달 열림추가
---
- ErrorPage.tsx : 위치 조정 및 홈버튼 수정
- App.tsx : 404page router 추가
---
- LIst.tsx : store 변수 정리 및 console.log 삭제
- Modal.tsx : 동일
- Header : 동일
- headerModal -> ProfileModal 위치 및 이름 변경
- feat/friendmanage
감사합니다~!!

✨ feat : 친구관리 기능 추가 + 404page 수정 + modal 코드 변수 정리 등

---

tailwind.config.js

- 애니메이션 보냅니다!
-  tailwind.config파일에 있고, 클래스에 animate-애니메이션명 입력하셔서 사용하시면 됩니다!!
- 화이팅~👍

💄 tailwind.config 파일에 scaleInTopLeft, scaleInTopRight 애니메이션 등록

---

src/App.tsx
src/css/font.css

- 기본 폰트를 설정하였습니다
style/font
감사합니다!!

💄 style: 전체 기본 폰트 설정

---

src/components/Modal/FriendManageModal.tsx
src/components/Modal/ProfileModal.tsx
src/components/Mui/List.tsx
src/routes/LayOut/Header.tsx
src/store/store.ts

- 친구관리 모달 디자인을 수정했습니다.
- 프로필 클릭 시 모달이 나오지 않는 버그를 수정했습니다.
-fix/reModal
- 이제 자러 가보겠습니다👀

🐛 fix: 친구관리 모달 디자인 및 프로필 모달 버그 수정

---

src/components/Mui/Calender.tsx
src/routes/Mypage/Mypage.tsx
src/routes/UserPage/UserPage.tsx

- 마이페이지 `<button>`을 Button 컴포넌트로 대체 
- UserPage에서 사용되지 않는 코드 삭제 
- Calendar 컴포넌트 날짜 클릭 시 색상이 정상적으로 바뀌도록 
- refactor/mypage ➡️ main

refactor: 마이페이지 리팩토링 

---

src/components/Modal/FriendManageModal.tsx
src/components/Modal/ProfileModal.tsx
src/components/Mui/Calender.tsx
src/css/tallwind.css

- 프로필 모달 친구목록에서 클릭시 프로필 보러가기로 수정
- 친구관리 스크롤 hover 시 나오게 수정
- 달력 클릭시 파랑색 수정
-style/modal
오늘도 파이팅⭐

📝 feat : 프로필모달 친구 프로필 보기 , 친구관리 스크롤 , 달력 클릭시 색 수정

---

src/App.tsx
src/api/axios.ts
src/components/Modal/ProfileModal.tsx
src/routes/Login/Login.tsx
src/routes/Main/Main.tsx
src/store/API.ts

- 로그인 시 로그인 유저 정보와 토큰값이 전역 변수, localStorage에 저장됩니다.
- 로그아웃 시 기존의 로그인 유저 정보와 토큰값이 초기화 됩니다.
- 로그인버튼, 로그아웃 버튼을 토큰 유무에 따라 변경시킵니다.
- axiosInstance 에 Authorization에 토큰값을 추가했습니다(아마 axiosInstance로 로그인 관련 post 보내면 작동될겁니다... 아..마도..?)
- feat/post-login-develop
- 로그인 정보는 이제 잘 담기는데 axiosInstance에 토큰값이 담기는지는 확인을 할 방법이 없네요 ㅎ
- 아무나 로그인 전용 post, get 요청 보내셔서 확인 부탁드려요!!!!🔥🔥

📝 feat/post-login-develop : 로그인 유저정보, 토큰 저장(로컬저장소 + 전역변수) + 로그아웃 시 초기화 + axiosInstance 토큰값 정보 추가

---

src/App.tsx
src/api/axios.ts
src/components/Modal/ProfileModal.tsx
src/routes/Main/Main.tsx
src/store/API.ts

- axiosInstance 토큰값 오류 수정했습니다.(토큰 기본값 null로 변경)
- 로그인 기본값 null로 변경했습니다. (store에서 불러올때 null 아님 연산자 ! 넣어서 타입에러 방지)
- 이제 로그인 정보를 전역으로 사용 가능합니다. 불러오고 싶은 컴포넌트에 다음과 같이 입력해 불러옵니다.
const user = useLoginStore((state) => state.user!); // 유저정보 불러오기(데이터타입 | null)이라 반드시 ! 연산자를 뒤에 붙여야 해요!!
const token = useLoginStore((state) => state.token); // 토큰값 불러오기
- feat/post-login-fix
- 로그인 정보 useLoginStore에 담겨있습니다!!
(*/ω＼*)b

🐛feat/post-login-fix : axiosInstance 토큰값 오류 수정 + 로그인 기본값 null로 변경

---

src/components/Modal/FriendManageModal.tsx

- 스크롤 hover 시 나오게 수정
- style/friendModal
- 파이팅~

💄 style: 친구관리 모달 스크롤 수정

---

src/routes/Join/Join.tsx

- 아이디/이메일 중복 여부를 확인하고 중복될 시 가입되지 못하도록 처리하였습니다.
feat/join
점점 코드가 난잡해져가네요,, 일단 기본 기능 구현하고 나중에 다듬도록 하겠습니다!
감사합니다!!

✨ 아이디/이메일 중복 방지 기능 추가

---

src/App.tsx
src/api/axios.ts
src/components/Modal/FriendManageModal.tsx
src/components/Modal/ProfileModal.tsx
src/main.tsx
src/routes/LayOut/Header.tsx
src/routes/Main/TopContents/TopContents.tsx

- main페이지 상단에 유저명 데이터바인딩 했습니다.
- header에 ProfileModal에 유저명 데이터바인딩 했습니다.
- header페이지 Main페이지와 넓이 같게 맞췄습니다.
- 친구관리 페이지 버튼 hover효과 수정했습니다.
- axios 문법을 수정했습니다.
- BrouserRouter컴포넌트를 main페이지에 App으로 이동했습니다..
- Feat/post-friends-develop
- 
^_^b

📝🩹💄Feat/post friends develop : Main페이지, 친구모달, header, axios 수정

---

src/api/api.d.ts
src/components/Modal/FriendManageModal.tsx
src/components/Modal/NonLoginFriendModal.tsx
src/components/Mui/List.tsx
src/routes/Main/RightComponent/FriendList.tsx

- follow페이지에 타입에러가 발생하던 현상을 수정했습니다.(followType을 새로 만들었습니다.)
- 기존에 메인페이지 친구목록 부분을 온라인유저 목록으로 바꿨습니다.(아직 개발단계)
- Feat/post-main-online
- 아무나 작업 시작하기 전에 확인 부탁드립니다!!!!

🚧 Feat/post main online : 온라인 유저 기능 구현 시작 + api.d.ts에 followType 생성

---

src/components/Community/PostPreview.tsx
src/routes/Community/Community.tsx
src/store/API.ts

- title속성 JSON문자열 파싱해서 이제 사용 가능합니당.
- 데이터 바인딩 이뿌게 부탁드려요!!
- feat/post-community
╰(*°▽°*)╯

📝 feat/post-community : 게시판 데이터바인딩(title 부분 파싱했습니당)

---

src/routes/LayOut/Header.tsx

- Header.tsx에 user변수 중복 선언 제거
- feat/post-main-fix
- 100번째 누구??

🐛 feat/post-main-fix : Header.tsx에 user변수 중복 선언 제거

---

src/api/api.d.ts
src/components/Community/PostPreview.tsx
src/routes/Community/Community.tsx

채널 버튼 추가, hover 했을 때 게시글 올라가게 수정했습니다
style/channel

💄 style: 게시판 스타일 개선

---

src/components/Community/ChannelButton.tsx
src/components/Community/Skeleton.tsx
src/routes/Community/Community.tsx

게시판 스켈레톤 추가 + 채널버튼 컴포넌트로 구분 + 채널 활성화 시 색 변하게 수정
style/channel
원래 게시판 api 받아오는 코드로는 로딩할 때 '스켈레톤  -> 게시글이 없습니다 -> 로딩된 화면' 순으로 출력돼서 게시판 api 받아오는 코드를 수정했는데 화면은 잘 굴러가는 것 같은데 로직이 확실히 맞는 건지는 모르겠습니당 ㅜㅜ
수정할 요소 있으면 말씀해주세용! 감사합니다!!

style: 게시판 스켈레톤 추가 + 채널버튼 수정

---

src/routes/Community/Community.tsx

♻️ refactor: 게시판 채널 코드 수정

---

src/api/api.d.ts
src/components/Mypage/Input.tsx
src/routes/Mypage/Mypage.tsx
src/routes/UserPage/UserPage.tsx
src/store/store.ts

- 마이페이지 import 구조 정리
- 화면에 수정 후 저장된 username, website, field 안 보이던 오류 해결
- 회원가입 직후에 닉네임 저장 안되는 오류 해결 
- ID 변경 불가능하게 변경 
- 닉네임이 없을 경우 빈 문자열로 설정 
- feat/post-userpage-fix ➡️ main
수고하셨습니다!! (●'◡'●)

fix: 마이페이지 오류 해결 
