src/components/editor/EditorModal.tsx

- 뒷배경 bg-opacity-70 잘못들어간거 확인해서 수정
feat/post-editor
자기전에 한번 더 체크했습니다.
나중에 버튼색이나 CKEditor도 제대로 적용해보겠습니다.

뒷배경 opacity-70으로 변경

---

src/App.tsx
src/components/headerModal/Modal.tsx
src/routes/LayOut/Header.tsx
src/routes/Mypage/Mypage.tsx

- 우측에 프로필 버튼이 2개 보이는 error 해결 
- 클릭 후 마이페이지로 이동 시 Modal이 자동으로 닫히도록
- 버튼 가운데로 정렬 
- 화면 좌측에 공백이 생겨 margin 값 조정 
- 마이페이지
- 로그인
- 회원가입 
- 로그아웃 ➡️ 로그인 
fix/header-route ➡️ main
화이팅 (❁´◡`❁)

fix: route 추가 + Header Modal error 해결 

---

src/App.tsx
src/components/Mui/Fab.tsx
src/components/howTime/HowTimeContents/HowTimeUnder.tsx
src/components/howTime/HowTimeModal.tsx
src/store/store.ts

1. 타이머 로컬스토리지 초기 설정을 루트폴더인 App.tsx에 하지 않고 Fab에 생성했음 
- => App.tsx파일로 옮김 
2.  useTimerStore의 시간값 초기설정에서 localStorage가 최초 생성되기 전에 store파일이 읽혀서 localStorage의 값을 찾을 수 없었음 
- => 예외 처리 했음(localStorage.getItem("TimerTime")
? JSON.parse(localStorage.getItem("TimerTime")!)[0])
- feat/post-main-fix
- 짜잔

🐛 fix: 타이머 로컬스토리지 관련 버그 수정

---

src/App.tsx
src/components/Mui/Fab.tsx
src/components/howTime/HowTimeContents/HowTimeContents.tsx
src/components/howTime/HowTimeContents/HowTimeTimer.tsx
src/components/howTime/HowTimeContents/HowTimeTop.tsx
src/components/howTime/HowTimeContents/HowTimeUnder.tsx
src/components/howTime/HowTimeModal.tsx
src/routes/Main/LeftContents/TimerComponent/Timer.tsx
src/routes/Main/LeftContents/TimerComponent/TimerComponent.tsx
src/store/store.ts

- 메인 페이지에 타이머 기능이 일부 활성화 되었습니다.(카운트 업 방식의 카운팅 기능)
- 타이머의 카운팅 기능이 라우팅 페이지 이동시 멈추는 현상을 수정했습니다(강사님이 도와주심, 하지만 인터벌 저장 변수가 컴포넌트 밖에 생성되어 있어 추후 zustand store에 따로 관리할 예정)
- 목표 시간 기능이 추가 되었습니다. 이제 몇 시간? 기능으로 정해진 시간을 목표시간으로 설정할 수 있습니다.(localStorage 활용, 추후에 오늘의 목표 설정하기 기능으로 목표시간 커스텀 기능 추가 예정) 
- 목표 시간을 활용해 추후에 목표 달성시 타이머 ui가 변하고 달성 여부를 boolean값으로 storage에 저장해 API에 저장시켜 사용할까 생각중입니다.
- 기능 개발하면서 각종 변수, storage형태가 변경되었습니다.(howTimeHoursSet, setHowTimeHoursSet 변수명 전부 changingHours, setChangingHours로 변경)
- port가 끊겨서 이미지 등이 안보입니당
- 제발 컴플릿 없기를......🙏🙏🙏

✅ feat/post-main: 메인페이지 타이머 기능 정형화 + 목표시간 추가 + 변수명, storage 대거 변경

---

src/components/Form/FormContainer.tsx
src/components/Form/Input.tsx
src/components/Form/LoginButton.tsx
src/components/common/Button.tsx
src/routes/Join/Join.tsx
src/routes/Join/JoinSuccess.tsx
src/routes/Login/Login.tsx

Input
- label이 수직 중앙에 오도록 수정
- label 앞 padding을 주었습니다.
- focus일 때 테두리 색 변경
- 사이즈를 줄였습니다.
FormContainer
- 사이즈를 줄이기 위해 width 값을 삭제하고, padding 값을 줄였습니다.
LoginButton
- 사이즈를 변경했습니다.
Button
- 사이즈를 하나 더 추가했습니다.
- xxl로 추가했는데, 다른 이름으로 하는 게 좋겠다면 말씀해주세용!
Join / Login/ JoinSuccess
- 전체적인 사이즈를 줄였습니다.
- 이미지 경로를 수정했습니다.
style/form
감사합니당! 수정사항 있으면 말씀해주세요!

Style/form 로그인/회원가입 전체적인 스타일 변경

---

src/components/editor/EditorModal.tsx
src/routes/Main/LeftContents/ButtonListComponent/ButtonListComponent.tsx

에디터를 닫을 때 `<p><br></p>` 가 생성 되어서
handleCancel 함수가 제대로 적용되지 않는 현상 수정.
ConfirmDialog가 제대로 출력됩니다.
fix/editor
에디터 부분의 주석처리가 없습니다. 
리액트 버전 확인해주세요!

fix: 에디터를 닫을 때, 제대로 안닫히는 현상 수정

---

src/components/Mui/Calender.tsx
src/components/Mui/Fab.tsx
src/components/Mui/List.tsx
src/routes/LayOut/Header.tsx
src/routes/Main/LeftContents/ButtonListComponent/LinkButton.tsx
src/routes/Main/Main.tsx
src/routes/Main/RightComponent/FriendList.tsx

- Fab.tsx에서 0 출력되는 콘솔 삭제
- Header.tsx 알람 이미지경로 수정
- etc폴더 삭제
- 메인페이지 버튼 텍스트 크기, 간격 조정
- 친구목록 스크롤바 디자인 변경(실선) + 상단 상자 색상 변경(#F0F5F8) + 하단 상자 제거
- calender 디자인 변경(색깔 넣고 그림자 처리 + 버튼 클릭 색상 변경(#F0F5F8))
- feat/post-main-style
- ㅎ.ㅎb

💄 feat/post-main-style : 메인페이지 디자인 변경 + 필요없는 폴더, 코드 삭제

---

package.json
src/components/editor/BlogEditor.tsx

프로젝트 실행마다 개발자 도구에 출력되는 findDomNode 에러 처리.
useRef이나 forwardRef으로는 해결이 불가능했음.
**react-quill-new로 재설치하면 호환성 문제 해결.**
fix/editor
pull 받으신 다음에,
**1. 기존 react-quill 제거**
pnpm remove react-quill
**2. react-quill-new 재설치**
pnpm install react-quill-new
경로설정이랑 코드 수정은 제가 해두었으니까 괜찮아욥.
참고로 리액트 19로 버전올려서 테스트해도 잘 됩니다.
혹시  개발자 도구에서 bullet 어쩌구~ 하는 에러 나오면 꼭 얘기해주세요.
터미널에서 나오는 source map 어쩌구~ 에러는 무시하셔도 됩니다.

fix : editor - findDomNode에러 처리 ✔

---

src/App.tsx
src/components/Mui/ResetFab.tsx
src/components/howTime/HowTimeContents/HowTimeTimer.tsx
src/css/font.css
src/routes/Main/LeftContents/TimerComponent/Timer.tsx
src/routes/Main/LeftContents/TimerComponent/TimerComponent.tsx
src/store/store.ts

- 타이머 리셋 버튼 추가 + 기능구현
- 메인페이지 높이값 screen으로 고정(overflow때문에)
- 타이머 폰트 교체(LAB디지털 폰트)
- 타이머 모양 변경 밑작업(컴포넌트에 square, circle 선택할 수 있게 미리 작업해놨습니다. polygonForm)
feat/post-main
- 디자인 짜봐야 하는데 부탁드립니다 디자인 박사님들 ^^7 특히 승연님 ^.^b 제일 감각적이셔

📝 feat/post-main 타이머 리셋버튼 개발 + 타이머 폰트 변경(LAB디지털), 메인페이지 높이값 screen으로 고정 

---

src/components/Mui/Calender.tsx
src/routes/Main/CenterContents/Calender/ToDo.tsx
src/routes/Main/CenterContents/Calender/ToDoEditor.tsx
src/routes/Main/CenterContents/Calender/ToDoListItem.tsx
src/routes/Main/LeftContents/TimerComponent/Timer.tsx
src/store/store.ts

- 달력 날짜 focus 시 색깔 파란색인 현상 수정
- 시계 형태 네모, 동그라미 선택 가능
- todo리스트 할 일 추가시 할 일 추가 버튼은 사라지고 input창만 남게 만듬
- 할 일 추가 모바일용 추가 버튼 생성
- todo리스트 체크상태 useState => 로컬 + store에 저장하도록 변경해서 창 새로고침 or 껏다 다시 켜도 초기화 되지 않음(local에 저장된 상태로 불러옴)
- feat/post-main-style
- 점점 코드가 복잡해지고 있어요🥲

📝 feat/post-main-style : 달력 포커스 스타일 오류 수정 + ToDo세부수정(버튼추가, 체크상태저장)

---

src/routes/Main/LeftContents/TimerComponent/Timer.tsx
src/routes/Main/LeftContents/TimerComponent/TimerComponent.tsx
src/store/store.ts

- Timer 컴포넌트 목표달성 알람음 활성/비활성 추가(alertSound, 기본값 false)
- 타이머 목표 달성 초기화 하고 다시 목표 달성시에도 트로피 모달이 다시 등장하게 수정(setTrophyModalNotViewed 함수 store에 추가)
-  Feat/post main develop
- 구우웃👍

📝 Feat/post main develop : 타이머 목표달성 알람음 활성/비활성 추가 + 타이머 목표 초기화시에도 다시 모달창 등장하게 수정

---

src/routes/Main/LeftContents/TimerComponent/Timer.tsx
src/store/store.ts

- 로그인시 목표달성 알람음 재생되던 현상 수정했습니다.
- alertSoundPlayed 전역변수를 만들고 true false 핸들러도 추가로 만들어 알람이 한 번 울리면 목표달성(achieve)가 false로 변경되지 않는 이상 다시 재생되지 않게 했습니다.
- 또로롱🎵

📝 feat/post-main : 로그인시 목표달성 알람음 재생되던 현상 수정(alertSoundPlayed 트리거 추가)

---

src/App.tsx
src/components/Modal/ProfileModal.tsx
src/routes/Join/Join.tsx
src/routes/Login/Login.tsx
src/routes/Main/Main.tsx
src/store/API.ts
src/store/store.ts

-  로그인시 유저데이터 API.ts store에 저장(API.ts) - 그런데 데이터가 새로고침시에 기본 설정값 {}으로 돌아감
- 로그아웃 클릭시 로그아웃 post 요청(제대로 가는건진 모르겠음)
-  Feat/post-login
- 받아온 전역변수를 콘솔출력 했습니다, 토큰이랑(Main.tsx에 콘솔출력함)
- 잘자요😇

📝 Feat/post login: 로그인시 유저데이터 API.ts store에 저장(API.ts), 로그아웃 클릭시 로그아웃 post 요청(제대로 가는건진 모르겠음)

---

src/components/Mui/ResetFab.tsx

- 타이머 초기화 ResetFab의 모달창에 style 추가 
- `<button>` 을 Button 컴포넌트로 대체 
style/reset-timer ➡️ main
- 삭제 버튼에 사용된 빨간색이 너무 강해보이면 알려주세요 😇

💄 style: 타이머 초기화 모달창 style 추가

---

src/App.tsx
src/components/Modal/ProfileModal.tsx
src/routes/Community/Community.tsx
src/routes/LayOut/Header.tsx
src/routes/Main/Main.tsx

- 타유저 프로필 보기 버튼을 누르면 프로필 페이지로 이동하도록 Link 추가
- 트로피 모달 오타 수정 h-[500px]
- Community route 추가 
- 경로가 '/'일 경우 '홈' 링크를 볼드 처리
- 경로가 '/community'일 경우 '게시글' 링크를 볼드 처리
- feat/user-profile-route ➡️ main
- Community route 때문에 이따 conflict 날 수도 있을 것 같습니다 🥲

feat: Community route, 타유저 프로필 페이지 Link 추가 

---

src/api/api.d.ts
src/routes/Mypage/Mypage.tsx
src/store/store.ts

- 마이페이지 API 연결
- 미이페이지 데이터 바인딩
- 프로필 편집 후 저장하면 서버에 데이터가 저장되도록 구현 
- api.d.ts 에서 isCover와 username 에는 옵셔널 연산자 `?` 를 사용
- feat/mypage-api ➡️ main
- API 명세서에 따라 website, field, 프로필 이미지를 PUT이 아니라 POST를 사용하도록 수정할 예정입니다. 
- 마이페이지에서 label을 수정할 예정입니다. (이름 -> id, 별명 -> 이름)

✨ feat: 마이페이지 API 연결 및 프로필 편집 시 데이터 저장 기능 구현

---

src/components/Mui/Calender.tsx
src/routes/Main/LeftContents/TimerComponent/Timer.tsx
src/routes/Main/RightComponent/RightContents.tsx

- Timer 동적 시,분,초 넓이값 50px 고정(이제 타이머 꿀렁꿀렁 거리지 않습니다!)
- 달력 년도 선택 색상 변경(#7EACB5)
- 그 외 안 쓰이는 import문 몇 개 삭제했습니다.
- feat/post-main-style
- 오늘은 여기까지.... 일찍 퇴근하겠슴다. (/ω＼)b

💄 feat/post-main-style : Timer 동적 시,분,초 넓이값 50px 고정 + 달력 년도 선택 색상 변경

---

src/api/api.d.ts
src/components/editor/BlogEditor.tsx
src/components/editor/EditorModal.tsx
src/routes/Main/LeftContents/ButtonListComponent/ButtonListComponent.tsx
src/store/postStore.ts
src/store/store.ts
tailwind.config.js

**에디터 내에서 채널이 선택 가능해졌습니다. (api 바인딩 완료)**
에러처리를 shake로 변경했습니다.
제목이나 컨텐츠가 비었을 때 & 저장에 실패 했을 때 에디터 창이 흔들립니다.
feat/editor-POSTAPI
각 채널을 선택해서 글을 작성후에 저장하시면 개발자 도구를 통해서도 알 수 있고,
postman으로도 확인 가능합니다.
저장 완료시 나오는 alert는 더 이쁜걸로 바꿔보겠습니당.

😎 feat: 에디터 - 원하는 채널 선택 가능, api 연결 완료

---

src/components/Mui/List.tsx

- 온라인 유저 리스트 데이터바인딩(커버 이미지는 아직 구현X)
- 유저 리스트 클릭시 모달창 데이터 바인딩은 아직 안했고 프로필 보기도 주소 연결을 아직 안했습니다.
- 오늘 일찍 자고 내일 다시 할게용 ㅎ
- 주말 마무리 잘 하세용⭐💡

📝 feat/post-main : 온라인 유저 리스트 데이터바인딩(커버 이미지는 아직 구현X)

---

src/api/api.d.ts
src/components/Modal/ProfileModal.tsx
src/components/Mui/List.tsx
src/routes/Main/RightComponent/OnlineList.tsx
src/routes/Main/RightComponent/RightContents.tsx

- 온라인 유저 기능 데이터바인딩 거의 완료 + FriendList.tsx에서 OnlineList.tsx로 파일명 변경
- 유저 이미지도 이제 데이터바인딩 됩니다
- feat/post-main-online
- 팔로우 유저도 데이터바인딩 하고 나면 이제 유저 페이지 데이터바인딩도 하겠습니다!!

📝 feat/post-main-online : 온라인 유저 기능 데이터바인딩 거의 완료 + FriendList.tsx에서 OnlineList.tsx로 파일명 변경

---

src/components/editor/BlogEditor.tsx
src/components/editor/LoginDialog.tsx
src/routes/Community/Community.tsx
src/routes/Main/LeftContents/ButtonListComponent/ButtonListComponent.tsx
src/store/store.ts

1. 에디터에서 선택한 채널과 게시판의 채널이 연동됩니다.
2. 컨텐츠의 내용에 p태그가 제거됐습니다.
3. 에디터의 채널 선택 부분과 제목이 겹쳐보이는 현상이 제거 됐습니다.
**4. 로그인한 회원만 글을 쓸 수 있게 로직을 변경했습니다.
임시적으로 Dialog로 각 페이지로 이동 가능하도록 연결되어있습니다. 추후에 디자인 변경 및 로직을 변경할때 참고하세요.**
feat/editor-channelBinding
**Merge 하실때, Community.tsx 부분에서 충돌이 난다면, 동적으로 channelId가 작성된 부분을 제거해주세요.**

✅feat : 로그인한 회원만 게시글 작성 가능, 게시판과 채널 연동, p태그 제거

---

src/api/api.d.ts
src/components/Community/PostPreview.tsx
src/components/editor/BlogEditor.tsx
src/components/editor/EditorModal.tsx
src/routes/Community/Community.tsx
src/store/postStore.ts
src/store/store.ts

1**. 에디터에서 업로드한 이미지가 썸네일로 적용 가능합니다. (API 바인딩 완료)**
2. 파일 업로드를 위한 버튼 구현
3. 이미지 버튼에 따른 에디터 상태정리 완료.
4. 버튼 옆에 이미지 파일의 이름이 나옵니다. (2줄이상이면 ... 으로)
**5. placeholder 오류 수정.
커서의 위치가 맞지 않는 부분을 수정했습니다.
조합문자가 입력됐을 때, placeholder가 사라지지 않는 오류를 수정했습니다.**
fix/editor-ImageBinding
픽스라고 생각했는데 feat이 맞는것 같습니다. 
파일 업로드 버튼의 위치가 애매할 수도 있습니다.
확인해주시고 좋은위치 찾으시면 알려주세요!
그 외에 자잘한 오류가 생기면 제보 부탁드립니다.

Feat: 에디터 이미지 바인딩 & 오류 수정

---

src/components/Community/PostPreview.tsx
src/components/Community/Skeleton.tsx

게시판에서 게시글 글쓴이 프로필/아이디 누르면 글쓴이 프로필로 연결되게 하였습니다.
게시글 모서리 둥글게 디자인 수정했습니당(+스켈레톤도 둥글게 수정)
feat/channel
감사합니당~~

✨ feat: 게시글 글쓴이 프로필 연결 + 게시글 둥글게 수정

---

src/components/Community/PostPreview.tsx
src/components/Community/Skeleton.tsx
src/routes/Community/Community.tsx
src/routes/Join/Join.tsx
src/routes/Join/JoinSuccess.tsx
src/routes/LayOut/CommunityLayout.tsx
src/routes/Login/Login.tsx

게시글 미리보기에서 글쓴유저 프로필을 눌렀을 때 , 그 글이 본인(현재 로그인한 유저)이 작성한 글이면 본인의 마이페이지로 이동하도록 하였습니다
게시글 썸네일/작성자 프로필 사진이 없는 경우 대체이미지가 나오도록 하였습니다.
스크롤 윗부분 안 보이는 문제를 수정했습니다
이미지 경로를 수정했습니다
feat/channel
감사합니다! 수정사항 있으면 말씀해주세요

✨ feat: 게시판 대체썸네일/프사 추가 + 본인 글이면 마이페이지로 연결 + 스크롤 수정 + 이미지 경로 수정

---

src/components/Mypage/Input.tsx

- 입력된 website 를 눌렀을 때  그 페이지가 새로운 창에서 열림
- http 으로 시작하지 않는 경우에는 website 앞에 https 를 붙여주고 정상적으로 작동 
- `<a>` 태그 `noopener noreferrer` 처리 
- feat/link-website ➡️ main
-  오류 생기면 알려주세요! 🙏

✨ feat: 마이페이지, 유저페이지 website 항목 하이퍼링크로 변환

---

src/components/404Page/ErrorPage.tsx
src/components/Community/PostPreview.tsx
src/routes/Join/Join.tsx
src/routes/Join/JoinSuccess.tsx
src/routes/LayOut/Header.tsx
src/routes/Login/Login.tsx

- 런타임 로고를 마스코트 이미지로 대체 
- style/mascot ➡️ main
- 깨지는 부분이 있으면 알려주세요 ♪(´▽｀)

💄 style: 런타임 로고를 마스코트 이미지로 대체

---

src/components/Post/PostButton.tsx
src/components/Post/PostButtonFieldCol.tsx
src/components/Post/PostButtonFieldRow.tsx

- 상세페이지에 사용할 버튼 컴포넌트 추가 
- 버튼 세트 추가 (row 방향 버전, col 방향 버전 구분)
- 좋아요 버튼 추가
- 댓글 버튼 추가
- 화면상단이동 버튼 추가
- feat/post-button-field ➡️ main
<br />
╰(*°▽°*)╯

feat: 상세페이지 버튼 컴포넌트,  좋아요/댓글/화면상단이동 버튼 세트 추가
